name: inject.example.coffee
description: A simple example of using package:inject

dependencies:
  inject:
    path: ../../package/inject

dev_dependencies:
  build_runner: ^1.10.1
  build_test: ^0.10.12+1
  build_web_compilers: ^2.11.0
  inject_generator:
    path: ../../package/inject_generator
  test: ^1.5.0
